- hosts: ciber-testbed
  become: yes

  vars:
    elasticsearch_user: elasticsearch
    elasticsearch_max_open_files: 65535

  tasks:
    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=2592000
      with_items:
        - nginx
        - git

    - name: Configure Testbed Nginx (proxy for tomcat and ciber.umd.edu)
      template: src=templates/nginx-testbed.conf.j2 dest=/etc/nginx/conf.d/testbed.conf

    - name: Configure Kibana Nginx
      template: src=templates/nginx-kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf

    - name: Configure Elastic Nginx
      template: src=templates/nginx-elastic.conf.j2 dest=/etc/nginx/conf.d/elastic.conf

    - name: Configure Nginx Passwords
      template: src=templates/passwords.j2 dest=/etc/nginx/passwords

    - name: Clone Elasticsearch Head
      git: repo=https://github.com/mobz/elasticsearch-head.git dest=/opt/eshead

    - name: Start services
      service: name={{ item }} enabled=yes state=restarted
      with_items:
        - nginx
