- hosts: ciber-testbed
  become: yes

  vars:
    elasticsearch_user: elasticsearch
    elasticsearch_max_open_files: 65535

  tasks:
    - apt_repository: repo="deb http://nginx.org/packages/ubuntu/ trusty nginx" state=present
    - apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - nginx
        - git
        - nfs-common

    - name: Kibana
      include: kibana.yml

    - name: Configure Testbed Nginx (proxy for tomcat and ciber.umd.edu)
      template: src=templates/nginx-testbed.conf.j2 dest=/etc/nginx/conf.d/testbed.conf

    - name: Configure Kibana Nginx
      template: src=templates/nginx-kibana.conf.j2 dest=/etc/nginx/conf.d/kibana.conf

    - name: Configure Elastic Nginx
      template: src=templates/nginx-elastic.conf.j2 dest=/etc/nginx/conf.d/elastic.conf

    - name: Configure Celery Flower
      template: src=templates/nginx-flower.conf.j2 dest=/etc/nginx/conf.d/flower.conf

    - name: Configure Indigo Nginx
      template: src=templates/nginx-indigo.conf.j2 dest=/etc/nginx/conf.d/indigo.conf

    - name: Configure Nginx Passwords
      template: src=templates/passwords.j2 dest=/etc/nginx/passwords

    - name: Clone Elasticsearch Head
      git: repo=https://github.com/mobz/elasticsearch-head.git dest=/opt/eshead

    - name: Mount CIBER XFER directory
      lineinfile: dest=/etc/fstab line="192.168.0.4:/export/ciber	/srv/ciber	nfs	_netdev,ro	0	0"
    - file: path=/srv/ciber state=directory
    - mount: name=/srv/ciber src=192.168.0.4:/export/ciber fstype=nfs state=mounted

    - name: Configure CIBER FTP-over-HTTP
      template: src=templates/nginx-ftphttp.conf.j2 dest=/etc/nginx/conf.d/ftphttp.conf

    - name: Start services
      service: name={{ item }} enabled=yes state=restarted
      with_items:
        - nginx
